---
- name: Create users and copy files into the users home dir
  hosts: all
  tasks:
    - name: Create multiple users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: Henry,b: 337,c: /home/Henry}
        - {a: Robert,b: 337,c: /tmp/Robert}
    - name: Copy files into users home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/Henry}
        - {a: /etc/group,b: /tmp/Robert}
...  
        
