---
- name: Configuring apache2/httpd based on Linux flavour
  hosts: all
  tasks:
    - name: Install apache2 on ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd on Redhat servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: Edit the index.html file
      copy:
        content: "IntelliQIT"
        dest: /var/www/html/index.html
    - name: Restart apache2 on the ubuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on the Redhat servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: Check apache2/httpd responce on all the servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.15.224
        - http://172.31.10.221
        - http://172.31.47.27
...

