---
- name: Create users ans create files/dirs in the user home dir
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: Create files/dirs in the users home dir
      file:
        name: "{{d}}"
        state: "{{e}}"
...


